name: Pylint

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: "3.12"
      - name: Install Pylint
        run: pip install pylint
      - name: Run Pylint
        run: pylint student_grades.py --fail-under=10
